# This workflow will push files to a server when you change your code.
#
# Intentionally does not delete any files from server, though existing ones may
# be overwritten.
name: Deploy site to SeedHost

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    environment:
      name: deployment-from-main
      url: https://www.aleph0.com/
    name: Deploy site
    steps:
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
        with:
          ssh-private-key: ${{ secrets.SEEDHOST_PRIVATE_KEY }}
          ssh-host: ssh.aleph0.com
      - uses: actions/checkout@v4.1.5
      - name: Copy to SeedHost
        run: rsync -avz --exclude .github --exclude .git --exclude .vscode "${GITHUB_WORKSPACE%/}/" chjones@ssh.aleph0.com:www/www.aleph0.com/~chjones/
